// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBanmraJo4BA4pb052XfKRK2MH-d9X5SlE',
    appId: '1:1065486424666:web:e91190ea257bf47d8c5663',
    messagingSenderId: '1065486424666',
    projectId: 'pos-flutter-a38c7',
    authDomain: 'pos-flutter-a38c7.firebaseapp.com',
    storageBucket: 'pos-flutter-a38c7.firebasestorage.app',
    measurementId: 'G-2P9CXJRF9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQpHFQ1ZoVCNvLO-XcAWgPU9b2QWry9ss',
    appId: '1:1065486424666:android:121185bcffe4d6fe8c5663',
    messagingSenderId: '1065486424666',
    projectId: 'pos-flutter-a38c7',
    storageBucket: 'pos-flutter-a38c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6EHsOYhuq-926uTT8d0O2bF9ySvf8Jw4',
    appId: '1:1065486424666:ios:00efb63fe8137bd28c5663',
    messagingSenderId: '1065486424666',
    projectId: 'pos-flutter-a38c7',
    storageBucket: 'pos-flutter-a38c7.firebasestorage.app',
    iosBundleId: 'com.example.tugasBesar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6EHsOYhuq-926uTT8d0O2bF9ySvf8Jw4',
    appId: '1:1065486424666:ios:00efb63fe8137bd28c5663',
    messagingSenderId: '1065486424666',
    projectId: 'pos-flutter-a38c7',
    storageBucket: 'pos-flutter-a38c7.firebasestorage.app',
    iosBundleId: 'com.example.tugasBesar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBanmraJo4BA4pb052XfKRK2MH-d9X5SlE',
    appId: '1:1065486424666:web:21e7ada60da25b0b8c5663',
    messagingSenderId: '1065486424666',
    projectId: 'pos-flutter-a38c7',
    authDomain: 'pos-flutter-a38c7.firebaseapp.com',
    storageBucket: 'pos-flutter-a38c7.firebasestorage.app',
    measurementId: 'G-PNKMXDVP6B',
  );
}
